#!/usr/bin/perl

use strict ;
use warnings ;
use IO::Uncompress::Gunzip qw(gunzip $GunzipError) ;

open(my $fh, "hello.txt.gz");
my $d = <$fh>;
close $fh;
my $x;
gunzip \$d => \$x
    or die "gunzip failed: $GunzipError\n";
print $x;
