#!/usr/bin/perl

use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use Minecraft;

use Data::Dumper;

if( @ARGV != 1 )
{
	print "$0 <world>\n";
	exit 1;
}
my( $worldname ) = @ARGV;

my $mc = new Minecraft( "$FindBin::Bin/saves" );
my $world = $mc->world( $worldname );
$world->{level}->debug;
exit;

